import { describe, it, expect, vi, beforeEach } from 'vitest';
import request from 'supertest';
import app from '../src/app';
import prisma from '../src/config/database';
import jwt from 'jsonwebtoken';
import { config } from '../src/config';
import { summaryService } from '../src/services/ai/summary.service';

vi.mock('../src/config/database', () => {
  return {
    default: {
      ticket: {
        findUnique: vi.fn(),
      },
    },
  };
});

vi.mock('../src/services/ai/summary.service', () => {
  return {
    summaryService: {
      summarize: vi.fn(),
    },
  };
});

describe('AI Endpoints', () => {
  let token: string;

  beforeEach(() => {
    vi.clearAllMocks();
    token = jwt.sign({ userId: 'agent-123', role: 'AGENT' }, config.jwt.secret, { expiresIn: '1h' });
  });

  describe('GET /api/ai/tickets/:ticketId/summary', () => {
    it('should successfully return the summary generated by the AI model', async () => {
      const mockTicket = {
        id: 'ticket-123',
        title: 'Network Issue',
        description: 'Internet connection is very slow.',
        category: 'IT',
        comments: [],
      };

      (prisma.ticket.findUnique as any).mockResolvedValue(mockTicket);
      (summaryService.summarize as any).mockResolvedValue({
        issue: 'Slow internet connection.',
        discussion: 'No discussion yet.',
        actionsTaken: 'None.',
        currentState: 'Awaiting support triage.',
        summary: 'Employee experiences slow internet speed.',
      });

      const res = await request(app)
        .get('/api/ai/tickets/ticket-123/summary')
        .set('Authorization', `Bearer ${token}`);

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
      expect(res.body.data.summary).toBe('Employee experiences slow internet speed.');
    });
  });
});
